In [8]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.read_csv("model_evaluations/model_evaluations/20_newsgroups_model_evaluation.csv")
df2 = pd.read_csv("model_evaluations/model_evaluations/bbc_news_model_evaluation.csv")
df3 = pd.read_csv("model_evaluations/model_evaluations/emails_model_evaluation.csv")
df4 = pd.read_csv("model_evaluations/model_evaluations/lyrics_model_evaluation.csv")
df5 = pd.read_csv("model_evaluations/model_evaluations/reuters_model_evaluation.csv")
df6 = pd.read_csv("model_evaluations/model_evaluations/seven_categories_model_evaluation.csv")

df = pd.concat([df1, df2, df3, df4, df5, df6])

In [6]:
df.head()

model_type  n_topics alpha_lda  coherence_u_mass  coherence_c_v  \
0        lda        10      auto         -1.647771       0.431769   
1        lda        15      auto         -1.691589       0.425324   
2        lda        20      auto         -2.084296       0.450647   
3        lda        25      auto         -1.980010       0.425205   
4        lda        30      auto         -2.358449       0.439588   

   coherence_c_uci  coherence_c_npmi  perplexity  
0        -0.403714          0.000311  254.612658  
1        -0.329512          0.005311  285.102388  
2        -0.600277          0.009207  302.912619  
3        -0.466475          0.003768  329.199261  
4        -0.678974          0.005376  357.273727

In [24]:
set(df["model_type"].tolist())

{'lda', 'lsi', 'lsi_tfidf', 'nmf', 'nmf_tfidf'}

In [9]:
list_coherence_c_v = df["coherence_c_v"].tolist()
list_coherence_c_uci = df["coherence_c_uci"].tolist()
list_coherence_c_npmi = df["coherence_c_npmi"].tolist()
list_coherence_u_mass = df["coherence_u_mass"].tolist()

# Combine lists into a 2D NumPy array
data = np.array([list_coherence_c_v, list_coherence_c_uci, list_coherence_c_npmi, list_coherence_u_mass])

# Compute the correlation matrix
correlation_matrix = np.corrcoef(data)

print(correlation_matrix)

[[ 1.          0.08102885  0.40020513 -0.07291317]
 [ 0.08102885  1.          0.9200607   0.93368676]
 [ 0.40020513  0.9200607   1.          0.78466187]
 [-0.07291317  0.93368676  0.78466187  1.        ]]


In [23]:
min(list_coherence_c_npmi)

-0.2030104682274317

In [14]:
# Create a DataFrame
df_corr = pd.DataFrame({
    'C_v': list_coherence_c_v,
    'C_uci': list_coherence_c_uci,
    'C_Npmi': list_coherence_c_npmi,
    'U_mass': list_coherence_u_mass
})

# Compute the correlation matrix
correlation_matrix = df_corr.corr()

# Convert the correlation matrix to a long format DataFrame
correlation_df = correlation_matrix.stack().reset_index()
correlation_df.columns = ['Variable1', 'Variable2', 'Correlation']

# Optionally, you can sort the DataFrame for better readability
correlation_df = correlation_df.sort_values(by=['Variable1', 'Variable2']).reset_index(drop=True)

print(correlation_df)

   Variable1 Variable2  Correlation
0     C_Npmi    C_Npmi     1.000000
1     C_Npmi     C_uci     0.920061
2     C_Npmi       C_v     0.400205
3     C_Npmi    U_mass     0.784662
4      C_uci    C_Npmi     0.920061
5      C_uci     C_uci     1.000000
6      C_uci       C_v     0.081029
7      C_uci    U_mass     0.933687
8        C_v    C_Npmi     0.400205
9        C_v     C_uci     0.081029
10       C_v       C_v     1.000000
11       C_v    U_mass    -0.072913
12    U_mass    C_Npmi     0.784662
13    U_mass     C_uci     0.933687
14    U_mass       C_v    -0.072913
15    U_mass    U_mass     1.000000


In [15]:
correlation_df.to_csv("CorrelationCoherenceMeasures.csv")